on:
  push:
    branches: develop

jobs:
  autopr:
    runs-on: ubuntu-latest
    name: Automatic PR
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Action
        uses: ./ # Uses an action in the root directory
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          base-branch: master
          head-branch: develop
          clubhouse-org: joequincy
          
